d!isitup
pedrofracassi/deku pull request #31
Opened 2018-02-17 21:30 UTC by PillGP

Usage: d!isitup <website url>
& that's it

2018-03-17 23:52 UTC, davipatury requested changes

2018-03-17 23:52 UTC, davipatury commented on commands/isitup.js
> +    else if(link.startsWith('https://')) return link.replace('https://', '');
```js
function checkHttp(link) {
    return link.replace(/^http(?:s)?:\/\//, '');
}

2018-03-17 23:52 UTC, davipatury commented on commands/isitup.js
> +                message.channel.startTyping();
`message.channel..startsTyping();` antes do `getStatus(...).then`

2018-03-17 23:52 UTC, davipatury commented on commands/isitup.js
> +                }
Coloca o `message.channel.send({embed});` depois dos ifs/elseifs pra evitar código repetido.

2018-03-17 23:52 UTC, davipatury commented on commands/isitup.js
> +const fetch = require('isomorphic-fetch');
Acho que tem como pegar o conteúdo do JSON usando o request, diminuindo assim o número de requisitos.

2018-03-22 12:17 UTC, PillGP commented
man wtf
not this

2018-03-22 12:17 UTC, closed without merging

2018-03-22 12:17 UTC, PillGP commented
(just check the `2e7a564` commit)

2018-03-22 12:18 UTC, PillGP commented
& i used isomorphic-fetch because request doesn't have a native promise base.